server:
  port: 8810
spring:
  application:
    name: OPENFEIGN-HYSTRIX
  cloud:
    consul:
      host: localhost
      port: 8500
feign:
  hystrix:
    enabled: true # 开启openfeign在调用服务过程中 开启hystrix支持 默认没有开启