server:
  port: 8801
spring:
  application:
    name: EUREKA-CLIENT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
#  instance:
#    lease-expiration-duration-in-seconds: 10 # 用来修改Eureka Server默认接受心跳的最大时间 默认为90s
#    lease-renewal-interval-in-seconds: 5 # 指定客户端多久想Eureka Server发一次心跳 默认为30s