server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
    fetch-registry: false  # 关闭eureka client 立即注册
    register-with-eureka: false # 关闭作为客户端向eureka注册
#  server:
#    enable-self-preservation: false # 关闭自我保护
#    eviction-interval-timer-in-ms: 3000 # 超时3s自动清除