server:
  port: 8807
spring:
  application:
    name: CATEGORY
  cloud:
    consul:
      port: 8500
      host: localhost
feign:
  client:
    config:
      # PRODUCT: # 指定服务器
      default: # 所有服务器
        connectTimeout: 5000 # 配置服务器连接超时时间
        readTimeout: 5000 # 配置服务器等待超时时间
        loggerLevel: FULL

# 展示openFeign日志
logging:
  level:
    com:
      xiehongyu:
        openfeign: debug

